### ISSUE TITLE
hxCodec doesn't work through hmm

### ISSUE THREAD

**Issue by xrou0x** [polybiusproxy/hxCodec#300] opened 2024-04-14 01:19 UTC
Not sure if this is a bug from hxCodec or hmm, but hxCodec doesn't work through hmm, and needs to be installed globally for it to work. I'm using the git version.

![image_2024-04-14_091842998](https://github.com/polybiusproxy/hxCodec/assets/118343420/7b9bf4b7-ec6f-4f44-a4a7-0a22cbeeedae)

**Comment by moxie-coder** [comment] 2024-04-14 03:39
this was already fixed in the develop branch

**Comment by xrou0x** [comment] 2024-04-14 07:04
I'm using the main branch though, do I really need to use that one?

**Closed** 2024-04-15 10:00 UTC

**Comment by EliteMasterEric** [comment] 2024-05-20 05:42
Fun fact, the ROOT cause of this issue was HaxeFoundation/haxelib#618 which has since been resolved.

You have to be using LATEST Haxelib though which we probably won't see a release for until Haxe 5.0.0.

**Comment by tobil4sk** [comment] 2025-01-29 16:52
> You have to be using LATEST Haxelib though which we probably won't see a release for until Haxe 5.0.0.

I noticed this was referenced in a few places. The issue was due to hxcpp, not haxelib, so you can get it working if you use hxcpp git.
